[package]
name = "bevy_mod_ffi_host_sys"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Low-level FFI bindings for bevy_mod_ffi hosts"

[dependencies]
bevy_mod_ffi_core = { path = "../core", version = "0.1.0" }
bevy = "0.17.3"
