[package]
name = "bevy_mod_ffi_guest_sys"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Low-level FFI bindings for bevy_mod_ffi guest side"

[dependencies]
bevy_mod_ffi_core = { path = "../core" }